import { z } from 'zod';

export const MqttNotificationConfigSchema = z.object({
    enabled: z.boolean().optional().describe('Whether MQTT outbound notifications are enabled.')
});

export type MqttNotificationConfig = z.infer<typeof MqttNotificationConfigSchema>;

const MqttEnabledSchema = z.object({
    enabled: z.literal(true),
    url: z.string().describe('Full broker URL, e.g. "mqtt://localhost:1883" or "mqtts://broker.example.com:8883".'),
    clientId: z.string().optional().describe('MQTT client identifier. Defaults to a random ID generated by the broker.'),
    username: z.string().describe('Username for broker authentication. For EMQX, this is the API Key.'),
    password: z.string().describe('Password for broker authentication. For EMQX, this is the Secret Key.'),
    topicPrefix: z.string().optional().describe('Optional prefix prepended to all MQTT topics, separated by "/". For example "home/office" produces topics like "home/office/miot-bridge/command".'),
    notifications: MqttNotificationConfigSchema.optional().describe('MQTT notification settings.')
});

const MqttDisabledSchema = z.object({
    enabled: z.literal(false).optional(),
    url: z.string().optional().describe('Full broker URL, e.g. "mqtt://localhost:1883" or "mqtts://broker.example.com:8883".'),
    clientId: z.string().optional().describe('MQTT client identifier. Defaults to a random ID generated by the broker.'),
    username: z.string().optional().describe('Username for broker authentication. For EMQX, this is the API Key.'),
    password: z.string().optional().describe('Password for broker authentication. For EMQX, this is the Secret Key.'),
    topicPrefix: z.string().optional().describe('Optional prefix prepended to all MQTT topics, separated by "/". For example "home/office" produces topics like "home/office/miot-bridge/command".'),
    notifications: MqttNotificationConfigSchema.optional().describe('MQTT notification settings.')
});

export const MqttConfigSchema = z.union([MqttEnabledSchema, MqttDisabledSchema]);

export type MqttConfig = z.infer<typeof MqttConfigSchema>;
