---
# Key must match subdirectory in packages/
http-provider: packages/http-provider/**
miot-device: packages/miot-device/**
otel: packages/otel/**
resilience: packages/resilience/**
tsed-http-provider: packages/tsed-http-provider/**
tsed-resilience: packages/tsed-resilience/**
ui-kit: packages/ui-kit/**
