import { AdditionalProperties, Description, Optional, Property, Required } from '@tsed/schema';

@AdditionalProperties(false)
export class MqttConfig {
    @Required()
    @Property(Boolean)
    @Description('Whether the MQTT integration is enabled. When true, the server connects to the configured broker on startup and subscribes to inbound command topics.')
    public enabled: boolean;

    @Required()
    @Property(String)
    @Description('Full broker URL, e.g. "mqtt://localhost:1883" or "mqtts://broker.example.com:8883".')
    public url: string;

    @Property(String)
    @Optional()
    @Description('MQTT client identifier. Defaults to a random ID generated by the broker.')
    public clientId?: string;

    @Required()
    @Property(String)
    @Description('Username for broker authentication. For EMQX, this is the API Key.')
    public username: string;

    @Required()
    @Property(String)
    @Description('Password for broker authentication. For EMQX, this is the Secret Key.')
    public password: string;

    @Property(String)
    @Optional()
    @Description('Optional prefix prepended to all MQTT topics, separated by "/". For example "home/office" produces topics like "home/office/miot-bridge/command".')
    public topicPrefix?: string;
}
