---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
  workflow_dispatch:

jobs:

  changes:
    name: Check changes
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    outputs:
      apps: ${{ steps.filter-apps.outputs.changes }}
      packages: ${{ steps.filter-packages.outputs.changes }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: 📂 Detect changed apps
        uses: dorny/paths-filter@v3
        id: filter-apps
        with:
          filters: .github/paths-filter-apps.yaml
      - name: 📂 Detect changed packages
        uses: dorny/paths-filter@v3
        id: filter-packages
        with:
          filters: .github/paths-filter-packages.yaml

  # lint-yaml:
  #   name: YAML lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
  #     - name: Run YAML lint
  #       uses: frenck/action-yamllint@v1.5
  #       with:
  #         strict: true

  lint-app-code:
    name: Code lint => ${{ matrix.app }}
    needs: changes
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.apps != '[]' }}
    strategy:
      matrix:
        app: ${{ fromJSON(needs.changes.outputs.apps) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Prepare repository
        uses: ./.github/actions/prepare
        with:
          TARGET_APP: ${{ matrix.app }}
          NODE_AUTH_TOKEN: ${{ secrets.TOOLKIT_HUB_PACKAGES }}
      - name: Run lint
        run: pnpm --filter ./${{ matrix.app }} lint

  build-app-code:
    name: Code build => ${{ matrix.app }}
    needs: changes
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.apps != '[]' }}
    strategy:
      matrix:
        app: ${{ fromJSON(needs.changes.outputs.apps) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Prepare repository
        uses: ./.github/actions/prepare
        with:
          TARGET_APP: ${{ matrix.app }}
          NODE_AUTH_TOKEN: ${{ secrets.TOOLKIT_HUB_PACKAGES }}
      - name: Run build
        run: pnpm --filter ./${{ matrix.app }} build

  test-app-code:
    name: Code test => ${{ matrix.app }}
    needs: changes
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.apps != '[]' }}
    strategy:
      matrix:
        app: ${{ fromJSON(needs.changes.outputs.apps) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Prepare repository
        uses: ./.github/actions/prepare
        with:
          TARGET_APP: ${{ matrix.app }}
          NODE_AUTH_TOKEN: ${{ secrets.TOOLKIT_HUB_PACKAGES }}
      - name: Run tests
        run: pnpm --filter ./${{ matrix.app }} test

  lint-dockerfile:
    name: Dockerfile lint
    needs: changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Dockerfile lint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./Dockerfile

  lint-package-code:
    name: Code lint => ${{ matrix.package }}
    needs: changes
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.packages != '[]' }}
    strategy:
      matrix:
        package: ${{ fromJSON(needs.changes.outputs.packages) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Prepare repository
        uses: ./.github/actions/prepare
        with:
          NODE_AUTH_TOKEN: ${{ secrets.TOOLKIT_HUB_PACKAGES }}
      - name: Run lint
        run: pnpm --filter ./packages/${{ matrix.package }} lint

  build-package-code:
    name: Code build => ${{ matrix.package }}
    needs: changes
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.packages != '[]' }}
    strategy:
      matrix:
        package: ${{ fromJSON(needs.changes.outputs.packages) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Prepare repository
        uses: ./.github/actions/prepare
        with:
          NODE_AUTH_TOKEN: ${{ secrets.TOOLKIT_HUB_PACKAGES }}
      - name: Run build
        run: pnpm --filter ./packages/${{ matrix.package }} build

  test-package-code:
    name: Code test => ${{ matrix.package }}
    needs: changes
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.packages != '[]' }}
    strategy:
      matrix:
        package: ${{ fromJSON(needs.changes.outputs.packages) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Prepare repository
        uses: ./.github/actions/prepare
        with:
          NODE_AUTH_TOKEN: ${{ secrets.TOOLKIT_HUB_PACKAGES }}
      - name: Run tests
        run: pnpm --filter ./packages/${{ matrix.package }} test
