---
name: Pull request

# yamllint disable-line rule:truthy
on:
  workflow_call:
  pull_request:
  push:
    branches:
      - main

jobs:
  changes:
    name: Check changes
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    outputs:
      apps: ${{ steps.filter-apps.outputs.changes }}
      packages: ${{ steps.filter-packages.outputs.changes }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: 📂 Detect changed apps
        uses: dorny/paths-filter@v3
        id: filter-apps
        with:
          filters: .github/paths-filter-apps.yaml
      - name: 📂 Detect changed packages
        uses: dorny/paths-filter@v3
        id: filter-packages
        with:
          filters: .github/paths-filter-packages.yaml

  build-app-images:
    name: Build ${{ matrix.app }} docker image
    needs: changes
    if: ${{ needs.changes.outputs.apps != '[]' }}
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        app: ${{ fromJSON(needs.changes.outputs.apps) }}
    uses: ./.github/workflows/docker-build-app.yaml
    secrets: inherit
    with:
      APP_PATH: ${{ matrix.app }}
      PUBLISH: false

  build-package-code:
    name: Code build => ${{ matrix.package }}
    needs: changes
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.packages != '[]' }}
    strategy:
      matrix:
        package: ${{ fromJSON(needs.changes.outputs.packages) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Prepare repository
        uses: ./.github/actions/prepare
        with:
          NODE_AUTH_TOKEN: ${{ secrets.TOOLKIT_HUB_PACKAGES }}
      - name: Run build
        run: pnpm --filter ./packages/${{ matrix.package }} build
